"""Tag models for recipe categorisation.

Tags are short keyword labels attached to recipes.  They can be applied
manually or generated by the ``TagExtractor`` LLM chain with a confidence
score.

Models:
    Tag: A reusable tag with an optional usefulness ranking.
    RecipeTagAssignment: A link between a recipe and a tag, carrying
        confidence and origin metadata.
"""

from pydantic import BaseModel


class Tag(BaseModel):
    """A reusable recipe tag.

    Attributes:
        name: Short keyword label (e.g. ``"vegetarian"``, ``"quick"``).
        usefulness: Non-negative integer ranking how useful this tag is
            for discovery.  Higher is more useful.  Defaults to ``0``.
    """

    name: str
    usefulness: int = 0


class RecipeTagAssignment(BaseModel):
    """An assignment of a tag to a recipe.

    Attributes:
        tag_name: The tag being assigned.
        confidence: Confidence score in the range ``[0.0, 1.0]``.
            ``1.0`` means certain; used by the AI extractor.
        origin: Source of the assignment - ``"ai"`` for
            ``TagExtractor`` output or ``"manual"`` for user input.
    """

    tag_name: str
    confidence: float
    origin: str
