"""initial_tables

Revision ID: 8932a1f058ac
Revises: 
Create Date: 2026-03-27 21:49:52.096113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8932a1f058ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('biography', sa.Text(), nullable=False),
    sa.Column('page_link', sa.String(length=1024), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('platform_id', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=256), nullable=False),
    sa.Column('meal_course', sa.String(length=64), nullable=True),
    sa.Column('recipe_json', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('usefulness', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('recipe_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('tag_name', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['tag_name'], ['tags.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'tag_name', name='uq_recipe_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_tags')
    op.drop_table('tags')
    op.drop_table('recipes')
    op.drop_table('authors')
    # ### end Alembic commands ###
